rust_library(
    name = "project1",
    srcs = glob(["src/*.rs"]),
    visibility=["PUBLIC"],
    deps = [
        "//project2:project2",
        "//third-party:futures"
    ],
)

# By convention our infrastructure generates test rules automatically by default
rust_test(
    name = "project1-unittest",
    srcs = glob(["src/*.rs"]),
    deps = [
        "//project2:project2",
        "//third-party:futures"
    ],
)